### ISSUE TITLE
How to get the host and port from URL?

### ISSUE THREAD

**Issue by Ar4enal** [cloudamqp/android-example#7]
Hi~
I want to get the host and port config from URL example. I dont know what does "gerbil.rmq.cloudamqp.com" mean in HOST and PORT settings.

factory.setUri(amqps://l**v:p***N@gerbil.rmq.cloudamqp.com/l**v);

But I need to use 
factory.setHost();
factory.setPort();

Can u help me please?

**Comment by dentarg** [comment]
The host is `gerbil.rmq.cloudamqp.com` and the port is either `5672` (`amqp://`) or `5671` if you are using TLS (`amqps://`). https://www.rabbitmq.com/networking.html#ports
